services:
  api:
    build: .
    container_name: app_reminder_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      JWT_SECRET: dev-secret
      JWT_EXPIRES_IN: 1d
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: app_reminder_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_reminder
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: