services:
  postgres:
    image: postgres:16
    container_name: app_reminder_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_reminder
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: